/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author daniel
 */
public class Control_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Control_Panel
     */
    public Control_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerJpanel = new javax.swing.JPanel();
        scheduleJpanel = new javax.swing.JPanel();
        control_panelJPanel = new javax.swing.JPanel();
        student_contolJPanel = new javax.swing.JPanel();
        editsClassesJPanel = new javax.swing.JPanel();
        classTextFieldJpanel = new javax.swing.JPanel();
        classNameJTextField = new javax.swing.JTextField();
        buttonsClassJpanel = new javax.swing.JPanel();
        editClassJButton = new javax.swing.JButton();
        newClassJButton = new javax.swing.JButton();
        deleteClassJButton = new javax.swing.JButton();
        classes_panelJPanel = new javax.swing.JPanel();
        classesJScrollPane = new javax.swing.JScrollPane();
        classesTable_JTable = new javax.swing.JTable();
        teachers_controlJPanel = new javax.swing.JPanel();
        teachersPanel_controllerJPanel = new javax.swing.JPanel();
        teacherBUttonsJPanel = new javax.swing.JPanel();
        editTeacherJButton = new javax.swing.JButton();
        newTeacherJButton = new javax.swing.JButton();
        deleteTeacherJButton = new javax.swing.JButton();
        formTEachersJPanel = new javax.swing.JPanel();
        teacherNameJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teacherNameJTextField = new javax.swing.JTextField();
        teacherDegreeJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        teacherDegreeJTextField = new javax.swing.JTextField();
        timeworkTeacherJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        teacherWorktimeJTextField = new javax.swing.JTextField();
        teachersTableJPanel = new javax.swing.JPanel();
        teachersJScrollPane = new javax.swing.JScrollPane();
        teachersJTabel = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        MenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        windowsJMenu = new javax.swing.JMenu();
        controlPanelJMenu = new javax.swing.JMenu();
        unhideControlPanelCheckMenuItem = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horarios");
        setExtendedState(6);
        setUndecorated(true);

        containerJpanel.setLayout(new javax.swing.BoxLayout(containerJpanel, javax.swing.BoxLayout.LINE_AXIS));

        scheduleJpanel.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout scheduleJpanelLayout = new javax.swing.GroupLayout(scheduleJpanel);
        scheduleJpanel.setLayout(scheduleJpanelLayout);
        scheduleJpanelLayout.setHorizontalGroup(
            scheduleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        scheduleJpanelLayout.setVerticalGroup(
            scheduleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        containerJpanel.add(scheduleJpanel);

        control_panelJPanel.setBackground(new java.awt.Color(255, 51, 51));
        control_panelJPanel.setLayout(new javax.swing.BoxLayout(control_panelJPanel, javax.swing.BoxLayout.Y_AXIS));

        editsClassesJPanel.setBackground(new java.awt.Color(0, 204, 204));
        editsClassesJPanel.setLayout(new javax.swing.BoxLayout(editsClassesJPanel, javax.swing.BoxLayout.Y_AXIS));

        classNameJTextField.setText("Escriba el nombre para un nuevo horario, o seleccione uno y editelo o borrelo");

        javax.swing.GroupLayout classTextFieldJpanelLayout = new javax.swing.GroupLayout(classTextFieldJpanel);
        classTextFieldJpanel.setLayout(classTextFieldJpanelLayout);
        classTextFieldJpanelLayout.setHorizontalGroup(
            classTextFieldJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classTextFieldJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        classTextFieldJpanelLayout.setVerticalGroup(
            classTextFieldJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classTextFieldJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editsClassesJPanel.add(classTextFieldJpanel);

        editClassJButton.setText("Editar");
        buttonsClassJpanel.add(editClassJButton);

        newClassJButton.setText("Nuevo");
        buttonsClassJpanel.add(newClassJButton);

        deleteClassJButton.setText("Eliminar");
        buttonsClassJpanel.add(deleteClassJButton);

        editsClassesJPanel.add(buttonsClassJpanel);

        classesTable_JTable.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        classesTable_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clase", "Lleno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        classesJScrollPane.setViewportView(classesTable_JTable);

        javax.swing.GroupLayout classes_panelJPanelLayout = new javax.swing.GroupLayout(classes_panelJPanel);
        classes_panelJPanel.setLayout(classes_panelJPanelLayout);
        classes_panelJPanelLayout.setHorizontalGroup(
            classes_panelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classes_panelJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        classes_panelJPanelLayout.setVerticalGroup(
            classes_panelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classes_panelJPanelLayout.createSequentialGroup()
                .addComponent(classesJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout student_contolJPanelLayout = new javax.swing.GroupLayout(student_contolJPanel);
        student_contolJPanel.setLayout(student_contolJPanelLayout);
        student_contolJPanelLayout.setHorizontalGroup(
            student_contolJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editsClassesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(classes_panelJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        student_contolJPanelLayout.setVerticalGroup(
            student_contolJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_contolJPanelLayout.createSequentialGroup()
                .addComponent(editsClassesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classes_panelJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        control_panelJPanel.add(student_contolJPanel);

        editTeacherJButton.setText("Editar");

        newTeacherJButton.setText("Nuevo");

        deleteTeacherJButton.setText("Eliminar");

        javax.swing.GroupLayout teacherBUttonsJPanelLayout = new javax.swing.GroupLayout(teacherBUttonsJPanel);
        teacherBUttonsJPanel.setLayout(teacherBUttonsJPanelLayout);
        teacherBUttonsJPanelLayout.setHorizontalGroup(
            teacherBUttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherBUttonsJPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(teacherBUttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteTeacherJButton)
                    .addGroup(teacherBUttonsJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(teacherBUttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editTeacherJButton)
                            .addComponent(newTeacherJButton))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        teacherBUttonsJPanelLayout.setVerticalGroup(
            teacherBUttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherBUttonsJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(editTeacherJButton)
                .addGap(12, 12, 12)
                .addComponent(newTeacherJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteTeacherJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre");

        teacherNameJTextField.setText("Escriba el nombre del docente");

        javax.swing.GroupLayout teacherNameJPanelLayout = new javax.swing.GroupLayout(teacherNameJPanel);
        teacherNameJPanel.setLayout(teacherNameJPanelLayout);
        teacherNameJPanelLayout.setHorizontalGroup(
            teacherNameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherNameJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherNameJTextField))
        );
        teacherNameJPanelLayout.setVerticalGroup(
            teacherNameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherNameJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherNameJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teacherNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setText("Curso(s)");

        teacherDegreeJTextField.setText("Separe con una coma si imparte mas de 1 curso");

        javax.swing.GroupLayout teacherDegreeJPanelLayout = new javax.swing.GroupLayout(teacherDegreeJPanel);
        teacherDegreeJPanel.setLayout(teacherDegreeJPanelLayout);
        teacherDegreeJPanelLayout.setHorizontalGroup(
            teacherDegreeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDegreeJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherDegreeJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
        );
        teacherDegreeJPanelLayout.setVerticalGroup(
            teacherDegreeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDegreeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherDegreeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teacherDegreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel3.setText("Horas");

        teacherWorktimeJTextField.setText("En numero ingrese las horas que debe cumplir el docente");

        javax.swing.GroupLayout timeworkTeacherJPanelLayout = new javax.swing.GroupLayout(timeworkTeacherJPanel);
        timeworkTeacherJPanel.setLayout(timeworkTeacherJPanelLayout);
        timeworkTeacherJPanelLayout.setHorizontalGroup(
            timeworkTeacherJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeworkTeacherJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherWorktimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
        );
        timeworkTeacherJPanelLayout.setVerticalGroup(
            timeworkTeacherJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeworkTeacherJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeworkTeacherJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(teacherWorktimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formTEachersJPanelLayout = new javax.swing.GroupLayout(formTEachersJPanel);
        formTEachersJPanel.setLayout(formTEachersJPanelLayout);
        formTEachersJPanelLayout.setHorizontalGroup(
            formTEachersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTEachersJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTEachersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherNameJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacherDegreeJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeworkTeacherJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formTEachersJPanelLayout.setVerticalGroup(
            formTEachersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTEachersJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherNameJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherDegreeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeworkTeacherJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teachersPanel_controllerJPanelLayout = new javax.swing.GroupLayout(teachersPanel_controllerJPanel);
        teachersPanel_controllerJPanel.setLayout(teachersPanel_controllerJPanelLayout);
        teachersPanel_controllerJPanelLayout.setHorizontalGroup(
            teachersPanel_controllerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachersPanel_controllerJPanelLayout.createSequentialGroup()
                .addComponent(teacherBUttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formTEachersJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        teachersPanel_controllerJPanelLayout.setVerticalGroup(
            teachersPanel_controllerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherBUttonsJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formTEachersJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        teachersTableJPanel.setBackground(new java.awt.Color(255, 255, 102));

        teachersJTabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        teachersJTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Docente", "Curso(s)", "Horas", "Cumplidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teachersJScrollPane.setViewportView(teachersJTabel);

        javax.swing.GroupLayout teachersTableJPanelLayout = new javax.swing.GroupLayout(teachersTableJPanel);
        teachersTableJPanel.setLayout(teachersTableJPanelLayout);
        teachersTableJPanelLayout.setHorizontalGroup(
            teachersTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teachersJScrollPane)
        );
        teachersTableJPanelLayout.setVerticalGroup(
            teachersTableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teachersJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout teachers_controlJPanelLayout = new javax.swing.GroupLayout(teachers_controlJPanel);
        teachers_controlJPanel.setLayout(teachers_controlJPanelLayout);
        teachers_controlJPanelLayout.setHorizontalGroup(
            teachers_controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teachersPanel_controllerJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teachersTableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        teachers_controlJPanelLayout.setVerticalGroup(
            teachers_controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachers_controlJPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teachersPanel_controllerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachersTableJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        control_panelJPanel.add(teachers_controlJPanel);

        containerJpanel.add(control_panelJPanel);

        fileJMenu.setText("Archivo");
        MenuBar.add(fileJMenu);

        windowsJMenu.setText("Ventana");

        controlPanelJMenu.setText("Panel de Control");

        unhideControlPanelCheckMenuItem.setSelected(true);
        unhideControlPanelCheckMenuItem.setText("Mostrar");
        unhideControlPanelCheckMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unhideControlPanelCheckMenuItemActionPerformed(evt);
            }
        });
        controlPanelJMenu.add(unhideControlPanelCheckMenuItem);

        windowsJMenu.add(controlPanelJMenu);

        MenuBar.add(windowsJMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unhideControlPanelCheckMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unhideControlPanelCheckMenuItemActionPerformed
        if(this.unhideControlPanelCheckMenuItem.isSelected())
            this.control_panelJPanel.setVisible(true);
        else
            this.control_panelJPanel.setVisible(false);
    }//GEN-LAST:event_unhideControlPanelCheckMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel buttonsClassJpanel;
    private javax.swing.JTextField classNameJTextField;
    private javax.swing.JPanel classTextFieldJpanel;
    private javax.swing.JScrollPane classesJScrollPane;
    private javax.swing.JTable classesTable_JTable;
    private javax.swing.JPanel classes_panelJPanel;
    private javax.swing.JPanel containerJpanel;
    private javax.swing.JMenu controlPanelJMenu;
    private javax.swing.JPanel control_panelJPanel;
    private javax.swing.JButton deleteClassJButton;
    private javax.swing.JButton deleteTeacherJButton;
    private javax.swing.JButton editClassJButton;
    private javax.swing.JButton editTeacherJButton;
    private javax.swing.JPanel editsClassesJPanel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JPanel formTEachersJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton newClassJButton;
    private javax.swing.JButton newTeacherJButton;
    private javax.swing.JPanel scheduleJpanel;
    private javax.swing.JPanel student_contolJPanel;
    private javax.swing.JPanel teacherBUttonsJPanel;
    private javax.swing.JPanel teacherDegreeJPanel;
    private javax.swing.JTextField teacherDegreeJTextField;
    private javax.swing.JPanel teacherNameJPanel;
    private javax.swing.JTextField teacherNameJTextField;
    private javax.swing.JTextField teacherWorktimeJTextField;
    private javax.swing.JScrollPane teachersJScrollPane;
    private javax.swing.JTable teachersJTabel;
    private javax.swing.JPanel teachersPanel_controllerJPanel;
    private javax.swing.JPanel teachersTableJPanel;
    private javax.swing.JPanel teachers_controlJPanel;
    private javax.swing.JPanel timeworkTeacherJPanel;
    private javax.swing.JCheckBoxMenuItem unhideControlPanelCheckMenuItem;
    private javax.swing.JMenu windowsJMenu;
    // End of variables declaration//GEN-END:variables
}
